#!/bin/bash
#This is common alias
which tree  >/dev/null 2>&1
if [ $? -ne 0 ];then
  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

alias grep='grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i'
alias psgrep='ps -ef|grep'
alias lsf='ls | sed "s:^:`pwd`/: "'
alias lsd='ls -F | grep '/$''
alias lf='ls -l | grep '^-''
alias findn='find . -name'
alias tg='tar zcvf'
alias tgz='tar zxvf'

#tmux alias
alias tmuxat='tmux at -t'
alias tmuxnw='tmux new -s'
alias tmuxls='tmux list-session'
alias tmuxkl='tmux kill-session -t'

#screenrc alias
alias screenat='screen -rd'
alias screennw='screen -S'

#git alias
alias gitad='git add'
alias gitst='git status .'
alias gitcl='git clone'
alias gitco='git commit'
alias gitpl='git pull --rebase'
alias gitdf='git diff'
alias gitps='git push'
alias gitck='git checkout'
alias gitbr='git branch'
alias glog='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'

#svn alias
alias svnu='svn up'
alias svnco='svn commit'
alias svnck='svn checkout'
alias svncl='svn cleanup'
alias svndf='svn diff'
